import {useEffect,useState} from 'react';
import {ArrowRight,ExternalLink,Flame} from 'lucide-react';
import {engineCatalog,applyEngine,findEngine} from './engines';
import type {Engine} from './engines';
import type {Stage} from './types';
import {PanelTabs} from './PanelTabs';
import {fmt} from './utils';

function EngineImage({engine}:{engine:Engine}) {
  const [failed,setFailed]=useState(false);
  return <figure className="engine-image">{engine.image_url&&!failed?<img src={engine.image_url} alt={`${engine.name} — ${engine.image_kind}`} onError={()=>setFailed(true)} referrerPolicy="no-referrer"/>:<div className="engine-image-empty"><Flame size={52}/><span>{failed?'Manufacturer image could not be loaded.':'Manufacturer image unavailable.'}</span></div>}<figcaption>{engine.image_kind??'Engine profile'}{engine.image_credit&&` · © ${engine.image_credit}`}<small>Static image. Online images require an internet connection.</small></figcaption></figure>;
}

export function EngineLibrary({stage,index,onApply}:{stage:Stage;index:number;onApply:(stage:Stage)=>void}) {
  const [page,setPage]=useState('catalog');
  const role=index===0?'booster':'upper',engines=engineCatalog.engines.filter(e=>e.role===role);
  const [selected,setSelected]=useState(findEngine(stage.engine_id)?.id??engines.find(e=>e.image_kind==='Manufacturer render')?.id??engines[0].id);
  const engine=engines.find(e=>e.id===selected)??engines[0];
  const [count,setCount]=useState(String(stage.engine_id===engine.id?stage.engine_count??1:engine.suggested_count));
  const [vacThrust,setVacThrust]=useState(engine.vacuum_thrust_n===null?(stage.engine_id===engine.id?String(stage.vacuum_thrust_n/(stage.engine_count??1)/1000):''):String(engine.vacuum_thrust_n/1000));
  const [vacIsp,setVacIsp]=useState(engine.isp_vacuum_s===null?(stage.engine_id===engine.id?String(stage.isp_vacuum_s):''):String(engine.isp_vacuum_s));
  const [seaIsp,setSeaIsp]=useState(stage.engine_id===engine.id?String(stage.isp_sea_level_s):''),[error,setError]=useState(''),[applied,setApplied]=useState('');
  useEffect(()=>{if(stage.engine_id===engine.id)setCount(String(stage.engine_count??1));},[stage.engine_id,stage.engine_count,engine.id]);
  const choose=(e:Engine)=>{const current=stage.engine_id===e.id;setSelected(e.id);setPage('profile');setCount(String(current?stage.engine_count??1:e.suggested_count));setVacThrust(e.vacuum_thrust_n===null?(current?String(stage.vacuum_thrust_n/(stage.engine_count??1)/1000):''):String(e.vacuum_thrust_n/1000));setVacIsp(e.isp_vacuum_s===null?(current?String(stage.isp_vacuum_s):''):String(e.isp_vacuum_s));setSeaIsp(current?String(stage.isp_sea_level_s):'');setError('');setApplied('');};
  const useCurrent=()=>{if(engine.vacuum_thrust_n===null)setVacThrust(String(stage.vacuum_thrust_n/(stage.engine_count??1)/1000));if(engine.isp_vacuum_s===null)setVacIsp(String(stage.isp_vacuum_s));setSeaIsp(String(stage.isp_sea_level_s));setError('');setApplied('');};
  const effectiveSeaIsp=engine.sea_level_thrust_n!==null&&Number(vacThrust)>0&&Number(vacIsp)>0?Number(vacIsp)*engine.sea_level_thrust_n/(Number(vacThrust)*1000):Number(seaIsp);
  const apply=()=>{try{onApply(applyEngine(stage,engine,Number(count),Number(vacThrust)*1000,Number(vacIsp),effectiveSeaIsp));setApplied(`${engine.name} applied to stage ${index+1}.`);setError('');}catch(e){setError((e as Error).message);setApplied('');}};
  const number=(label:string,value:string,change:(s:string)=>void,unit:string,readOnly=false)=> <label className="field"><span className="field-label">{label}<small>{readOnly?'Source reference':'Model input'}</small></span><span className="input-wrap"><input type="number" min={unit==='engines'?1:0} max={unit==='engines'?40:undefined} step={unit==='engines'?1:'any'} value={value} onChange={e=>{change(e.target.value);setApplied('');}} readOnly={readOnly} placeholder="Required"/><span className="input-unit">{unit}</span></span></label>;
  return <section className="card engine-library"><div className="card-heading"><div><span className="eyebrow">Engine library · stage {index+1}</span><h3>{index===0?'Booster propulsion':'Upper-stage propulsion'}</h3></div><span className="badge">{engines.length} engines</span></div><p className="muted">Browse an engine, review its profile, then apply it to this stage.</p><div className="section-tabs library-tabs" role="tablist" aria-label="Engine library sections">{['catalog','profile','configuration'].map(id=><button key={id} role="tab" aria-selected={page===id} onClick={()=>setPage(id)}>{id==='catalog'?'Engine catalog':id==='profile'?'Engine profile':'Apply to stage'}</button>)}</div>{page==='catalog'&&<div className="engine-options" aria-label={`Stage ${index+1} engine catalog`}>{engines.map(e=><button key={e.id} className={`engine-option ${e.id===engine.id?'active':''}`} aria-pressed={e.id===engine.id} onClick={()=>choose(e)}><span>{e.name}<small>{e.manufacturer}</small></span><ArrowRight size={15}/></button>)}</div>}{page==='profile'&&<PanelTabs key={engine.id} label="Engine profile pages" pages={[
{id:'image',label:'Overview',content:<div className="engine-overview"><EngineImage key={engine.id} engine={engine}/><div><h2>{engine.name}</h2><p>{engine.description}</p><button className="button primary" onClick={()=>setPage('configuration')}>Configure {engine.name}<ArrowRight size={15}/></button></div></div>},
{id:'specs',label:'Specifications',content:<div className="engine-profile"><h2>{engine.name}</h2><dl><div><dt>Manufacturer</dt><dd>{engine.manufacturer}</dd></div><div><dt>Launch vehicles</dt><dd>{engine.vehicles}</dd></div><div><dt>Propellants</dt><dd>{engine.propellants}</dd></div><div><dt>Cycle</dt><dd>{engine.cycle}</dd></div><div><dt>Vacuum thrust / engine</dt><dd>{engine.vacuum_thrust_n===null?'Not published here':`${fmt(engine.vacuum_thrust_n/1000,1)} kN`}</dd></div><div><dt>Sea-level thrust / engine</dt><dd>{engine.sea_level_thrust_n===null?'Not published here':`${fmt(engine.sea_level_thrust_n/1000,1)} kN`}</dd></div><div><dt>Vacuum Isp reference</dt><dd>{engine.isp_vacuum_s===null?'Not published here':`${engine.isp_vacuum_s} s`}</dd></div>{engine.isp_unspecified_s!==null&&<div><dt>Published Isp · pressure unspecified</dt><dd>{engine.isp_unspecified_s} s</dd></div>}</dl></div>},
{id:'sources',label:'Source notes',content:<div className="engine-profile"><span className="eyebrow">Reference checked {engineCatalog.version}</span><h2>{engine.name}</h2><a className="engine-source" href={engine.source_url} target="_blank" rel="noreferrer">Manufacturer / agency reference <ExternalLink size={13}/></a><p>{engine.notes}</p><p className="field-hint">Manufacturer reference values do not certify a mission-specific engine configuration.</p></div>}
]}/>}{page==='configuration'&&<div className="engine-apply"><h3>Configure for stage {index+1}</h3><p className="field-hint">Unpublished values are supplied by you. Sea-level Isp is the pressure-response input for this point-mass model; vacuum engines are not certified for sea-level operation. Masses remain your stage design.</p><div className="fields two">{number('Number of engines',count,setCount,'engines')}{number('Vacuum thrust per engine',vacThrust,setVacThrust,'kN',engine.vacuum_thrust_n!==null)}{number('Vacuum Isp',vacIsp,setVacIsp,'s',engine.isp_vacuum_s!==null)}{engine.sea_level_thrust_n!==null?<div className='field'><span className='field-label'>Sea-level Isp model value<small>Derived from source thrust</small></span><strong>{Number.isFinite(effectiveSeaIsp)&&effectiveSeaIsp>0?fmt(effectiveSeaIsp,3)+' s':'Supply vacuum thrust and Isp'}</strong></div>:number('Sea-level Isp model value',seaIsp,setSeaIsp,'s')}</div><button className="text-button" onClick={useCurrent}>Use current stage values for missing inputs</button><p className="field-hint">Initial throttle range: {fmt((engine.throttle_min??1)*100,1)}–100%. Initial ignition limit: {engine.ignition_limit}. Review these mission settings in Engine operation.</p>{error&&<p role="alert" className="error">{error}</p>}{applied&&<p role="status" className="engine-applied">{applied}</p>}<button className="button primary" onClick={apply}>Use {engine.name} on stage {index+1}<ArrowRight size={15}/></button></div>}</section>;
}
