import type {Scenario,StageMassBounds,Result} from './types';
import {suggestedMassBounds,sizingValid} from './sizing';
import {fmt} from './utils';
import {PanelTabs} from './PanelTabs';

export function StageSizing({scenario,onChange}:{scenario:Scenario;onChange:(scenario:Scenario)=>void}) {
  const enabled=!!scenario.vehicle.optimize_stage_masses;
  const update=(patch:Partial<Scenario['vehicle']>)=>onChange({...scenario,vehicle:{...scenario.vehicle,...patch}});
  return <section className="card stage-sizing"><div className="card-heading"><div><span className="eyebrow">Joint vehicle & flight optimization</span><h3>Stage sizing</h3></div></div><PanelTabs label="Stage sizing pages" pages={[{id:'policy',label:'Sizing policy',content:<><label className="sizing-toggle"><input type="checkbox" checked={enabled} onChange={e=>onChange({...scenario,vehicle:{...scenario.vehicle,optimize_stage_masses:e.target.checked},constraints:{...scenario.constraints,solver_method:e.target.checked?'mission':scenario.constraints.solver_method}})}/>Optimize stage masses</label><p className="field-hint">Dry mass and fuel loads can change with the flight controls. Payload, engines and engine count stay fixed.</p><label className="field"><span className="field-label">Minimum initial thrust-to-weight</span><span className="input-wrap"><input type="number" min={1.001} max={5} step={.01} value={scenario.vehicle.minimum_initial_twr??1.05} onChange={e=>{const v=e.currentTarget.valueAsNumber;if(Number.isFinite(v))update({minimum_initial_twr:v});}}/><span className="input-unit">T/W</span></span></label><p className="field-hint">Preliminary sizing assumptions. Final designs are checked by continuous flight replay; this model does not certify tank strength or vehicle geometry.</p></>},...scenario.vehicle.stages.map((stage,index)=>{
    const b=stage.mass_bounds??suggestedMassBounds(stage);
    const change=(key:keyof StageMassBounds,value:number)=>{const stages=[...scenario.vehicle.stages];stages[index]={...stage,mass_bounds:{...b,[key]:value}};update({stages});};
    const field=(label:string,key:keyof StageMassBounds,scale=1000,unit='t')=><label className="field"><span className="field-label">{label}</span><span className="input-wrap"><input type="number" value={Number((b[key]/scale).toPrecision(12))} min={0} step="any" onChange={e=>{const v=e.currentTarget.valueAsNumber;if(Number.isFinite(v))change(key,v*scale);}}/><span className="input-unit">{unit}</span></span></label>;
    return {id:`stage${index+1}`,label:`Stage ${index+1} bounds`,content:stage.engine_type==='solid'?<p className="field-hint">Solid motor masses and burn profiles remain fixed.</p>:<><p className="field-hint">{stage.mass_bounds?'User-defined':'Suggested'} bounds. Dry mass ≥ fixed hardware + tank/structure ratio × propellant. Hardware must include all engines and supporting systems.</p><div className="fields three">{field('Minimum dry mass','dry_mass_min_kg')}{field('Maximum dry mass','dry_mass_max_kg')}{field('Minimum propellant load','propellant_min_kg')}{field('Maximum propellant load','propellant_max_kg')}{field('Fixed hardware mass','hardware_mass_kg')}{field('Tank / structure ratio','tank_structure_ratio',.01,'%')}</div>{!enabled&&<p className="field-hint">Mass optimization is disabled; these bounds are retained for later use.</p>}</>};})]}/>{!sizingValid(scenario)&&<p className="error" role="alert">Correct the mass bounds and structural allowance. The minimum fuel load must fit within maximum dry mass, and initial T/W must be above one.</p>}</section>;
}

export function SizedDesign({result}:{result:Result}) {
  const sizing=result.stage_sizing;if(!sizing)return null;
  return <section className="card"><span className="eyebrow">Joint stage sizing</span><h3>Optimized vehicle design</h3><p className="field-hint">Initial mass: {fmt(sizing.original_initial_mass_kg/1000,2)} t input → {fmt(sizing.optimized_initial_mass_kg/1000,2)} t replayed. Payload and engines are fixed. Initial pad T/W: {fmt(sizing.verified_initial_pad_twr,3)}; required ≥ {fmt(sizing.minimum_initial_twr,3)}.</p><div className="table-scroll"><table><thead><tr><th>Stage</th><th>Input dry</th><th>Replay dry</th><th>Input propellant</th><th>Replay propellant</th><th>Mass bounds</th></tr></thead><tbody>{sizing.stages.map(row=><tr key={row.stage_index}><td>{row.stage}</td><td>{fmt(row.original_dry_mass_kg/1000,2)} t</td><td>{fmt(row.dry_mass_kg/1000,2)} t</td><td>{fmt(row.original_propellant_mass_kg/1000,2)} t</td><td>{fmt(row.propellant_mass_kg/1000,2)} t</td><td>{row.fixed_solid_motor?'Fixed solid motor':sizing.bounds_verified?'Verified':'Not verified'}</td></tr>)}</tbody></table></div><p className="field-hint">{sizing.structural_model}</p></section>;
}
