export interface LaunchSite { launch_site_id?:string|null; azimuth_sectors_deg?:[number,number][]; range_source?:string; latitude_deg:number; longitude_deg:number; elevation_m:number; geoid_height_m:number; elevation_source:string; elevation_resolution_arcsec:number|null; surface:'auto'|'land'|'ocean'; elevation_resolved:boolean; epoch:string }
export interface Environment { model:'msis'|'standard'; solar_mode:'automatic'|'manual'|'nominal'; f107:number; f107_average:number; ap:number }
export interface StageMassBounds {dry_mass_min_kg:number;dry_mass_max_kg:number;propellant_min_kg:number;propellant_max_kg:number;hardware_mass_kg:number;tank_structure_ratio:number}
export interface Stage { mass_bounds?:StageMassBounds|null; name:string; engine_id?:string|null; engine_count?:number; engine_catalog_version?:string|null; engine_type:'liquid'|'solid'; dry_mass_kg:number; propellant_mass_kg:number; vacuum_thrust_n:number; isp_sea_level_s:number; isp_vacuum_s:number; reference_area_m2:number; cd:number; cd_table:[number,number][]; throttle_min:number; throttle_max:number; ignition_limit:number; separation_delay_s:number; max_thrust_velocity_angle_deg:number; space_thrust_velocity_angle_deg?:number|null; solid_burn_curve:[number,number][] }
export interface Constraints { vertical_ascent_s:number; max_dynamic_pressure_pa:number|null; max_load_factor_g:number|null; max_mission_duration_s:number; solver_budget_s:number; max_iterations:number; solver_method?:"mission"|"legacy"; control_nodes?:number; mesh_segments?:number; refinement_levels?:number; max_topologies?:number }
export interface Target { perigee_altitude_m:number|null; apogee_altitude_m:number|null; inclination_deg:number|null; raan_deg:number|null; argument_of_periapsis_deg:number|null; arrival_phase_deg:number|null; altitude_tolerance_m:number; angle_tolerance_deg:number; arrival_time_min_s?:number|null; arrival_time_max_s?:number|null }
export interface BudgetAssumptions {gravity_loss_m_s:number;drag_loss_m_s:number;steering_loss_m_s:number;contingency_percent:number}
export interface BudgetStage {stage:string;stage_index:number;ascent_delta_v_m_s:number;ascent_fuel_kg:number;arrival_fuel_kg:number;protected_reserve_kg:number;required_fuel_kg:number;available_fuel_kg:number;shortfall_kg:number;fuel_after_ascent_kg:number;resizable:boolean}
export interface BudgetSizing {available:boolean;reason?:string;total_required_fuel_kg?:number;total_available_fuel_kg?:number;stage_shortfall_kg?:number;arrival_fuel_kg?:number;protected_reserve_kg?:number;initial_mass_kg?:number;initial_pad_twr?:number|null;within_stage_capacities?:boolean;stages:BudgetStage[]}
export interface MissionBudget {version:number;assumptions:BudgetAssumptions;reference:{perigee_altitude_m:number;apogee_altitude_m:number;parking_altitude_m:number;departure_inclination_deg:number;plane_change_deg:number};components:{name:string;delta_v_m_s:number}[];coplanar_arrival_delta_v_m_s:number;tiers:(BudgetSizing&{name:string;delta_v_m_s:number})[];payload_sweep:(BudgetSizing&{payload_kg:number})[];warnings:string[];method:string;reserve_policy:string;onward_geo:null|{remaining_delta_v_m_s:number;remaining_fuel_kg:number;coplanar_delta_v_m_s:number;coplanar_fuel_kg:number|null;aligned_node_geo_delta_v_m_s:number;aligned_node_geo_fuel_kg:number|null;note:string}}
export interface Scenario { schema_version:1; name:string; launch:LaunchSite; environment:Environment; vehicle:{optimize_stage_masses?:boolean;minimum_initial_twr?:number;payload_mass_kg:number; expected_initial_mass_kg:number|null; stages:Stage[]}; constraints:Constraints; target:Target; objective:'propellant'|'time';budget?:BudgetAssumptions }
export interface Orbit { bound:boolean; semi_major_axis_m:number|null; eccentricity:number; perigee_altitude_m:number; apogee_altitude_m:number|null; inclination_deg:number; raan_deg:number|null; argument_of_periapsis_deg:number|null; arrival_phase_deg:number|null; phase_definition:string }
export interface SeriesRow { time_s:number; stage_index:number; phase:string; latitude_deg:number; longitude_deg:number; altitude_m:number; inertial_speed_m_s:number; relative_speed_m_s:number; mass_kg:number; active_propellant_kg:number; thrust_n:number; throttle:number; density_kg_m3:number; temperature_k:number|null; pressure_pa:number; mach:number|null; dynamic_pressure_pa:number; load_factor_g:number; thrust_velocity_angle_deg:number; position_gcrs_m:number[]; velocity_gcrs_m_s:number[] }
export interface StageSizingReport {enabled:boolean;bounds_verified:boolean;original_initial_mass_kg:number;optimized_initial_mass_kg:number;payload_mass_kg:number;minimum_initial_twr:number;verified_initial_pad_twr?:number;structural_model:string;stages:{stage_index:number;stage:string;original_dry_mass_kg:number;original_propellant_mass_kg:number;dry_mass_kg:number;propellant_mass_kg:number;bounds:StageMassBounds;minimum_structural_dry_mass_kg:number;fixed_solid_motor:boolean}[]}
export interface Result {consistency?:ConsistencyReport;input_scenario?:Scenario;stage_sizing?:StageSizingReport; status:string; termination_reason?:string; orbit:Orbit; target_comparison:{parameter:string;target:number;actual:number|null;error:number|null;tolerance:number;within_tolerance:boolean}[]; summary:Record<string,number>; constraint_checks:Record<string,boolean>; propellant_ledger:{stage:string;initial_kg:number;burned_kg:number;remaining_kg:number;discarded_kg:number}[]; events:{time_s:number;event:string;stage:string;discarded_dry_mass_kg?:number;discarded_propellant_kg?:number}[]; series:SeriesRow[]; actual_orbit_curve:number[][]; target_orbit_curve:number[][]; scenario:Scenario; flight_plan:unknown; metadata:Record<string,unknown>; warnings:string[]; optimizer:{method:string;iterations:number;elapsed_s:number;messages:string[];objective:string;note:string;termination_reason?:string;total_budget_exhausted?:boolean;search_elapsed_s?:number;invalid_candidates?:number;numerical_failures?:number;verification_failures?:string[];mission?:{verified_target_error?:number;legal_structure_count:number;selected_structure_count:number;structures:string[];derivatives:string;phases:{kind:string;stage_index:number;time_s:number;duration_s:number;control_nodes?:number}[]};searches?:{construction_elapsed_s?:number|null;solve_elapsed_s?:number;mesh_segments?:number;control_nodes?:number;refinement_level?:number;pre_polish_replay_status?:string;replay_target_error?:number;replay_status?:string;template:number;burn_count:number;stop_reason:string;iterations:number;elapsed_s:number;invalid_candidates?:number;numerical_failures?:number;solver_messages:string[]}[]} }
export interface Job { id:string; state:'queued'|'running'|'completed'|'cancelled'|'failed'; phase?:string; elapsed_s?:number; iteration?:number; target_error_score?:number; rejected_candidates?:number; constraint_violation?:number; best_continuous_error?:number|null; feasible_flight_retained?:boolean; score_units?:string; error?:string; outcome?:string }
export interface AtmospherePreview {metadata:Record<string,unknown>;profile:{altitude_m:number;density_kg_m3:number;temperature_k:number;pressure_pa:number;sound_speed_m_s:number}[]}

export interface SiteRecommendation { id:string;name:string;pad:string;country:string;status:string;range_verified:boolean;azimuth_sectors_deg:[number,number][];range_reference:string;range_source_url:string|null;recommended_azimuth_deg:number;reference_inclination_deg:number;minimum_plane_change_deg:number;plane_change_estimate_m_s:number;rotation_benefit_m_s:number;ranking_cost_m_s:number;launch_windows_utc:string[] }
export interface SiteScreening {sites:SiteRecommendation[];note:string;window_note:string}

export interface ConsistencyReport {
  mission_budget?:MissionBudget;
  status:string;ideal_delta_v_m_s:number;energy_screen_delta_v_m_s:number;optimistic_margin_m_s:number;
  initial_rotation_speed_m_s:number;initial_twr:number;maximum_pad_twr:number;optimistic_payload_ceiling_kg:number|null;
  stages:{stage:string;ignition_mass_kg:number;burnout_mass_kg:number;ideal_delta_v_m_s:number;vacuum_initial_twr:number;full_throttle_burn_s:number}[];
  findings:{code:string;severity:'warning'|'info';title:string;message:string}[];
  diagnostic:{final_radial_speed_m_s:number|null;maximum_altitude_m:number|null;propellant_balance_error_kg:number;optimizer_budget_exhausted:boolean|null}|null;
  assumptions:string;source_url:string;
}
